# site settings
title: RENTECH COMPANY - RTC
subtitle: 'Tehnologija na temeljima tradicije!
email: rentech.ivan@outlook.com
description: 'Panta rei – sve teče, sve se mijenja. <br>  Gradilište nije samo beton i čelik – to je organizam koji živi, diše i napreduje. Zato je bitno ići u korak s novom tehnologijom. <br> Mi smo ovdje da osiguramo da sve teče kako treba – od prvog papira na stolu do zadnjeg vijka na konstrukciji.'
baseurl:
url: https://LukaviLisac.github.io 
author: Ivan 
street_address: Markuševečka cesta
city: Zagreb
state: Grad Zagreb
zip_code: 10000
country: Hrvatska
phone: (+385) 91 11 55 207

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://LukaviLisac.github.io
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
