name: Build Workflow

on:
  push:
    branches:
      - main

jobs:
  build_only:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install dependencies
        run: bundle install

      - name: Run build
        run: bundle exec rake build